### ISSUE TITLE
Module Structure

### ISSUE THREAD

**Issue by pixeldesu** [Nightbug/servunite#1]
This is a discussion for module structure and what should be included in the base of each, so we have a general idea of everything.

### Location

Modules should be located in `lib/modules`, this makes the most sense.

### Configuration

As there will be only one global configuration file, each module can (if necessary) get configuration variables from a specified block. This block should be named like the module so no confusion is caused.

**Example:**

```yaml
mumble:
  address: "mumble.example.com"
  port: "64738"
  username: "servunite"

irc:
  address: "irc.example.com"
  port: "6667"
  username: "servunite"
  realname: "ServUnite Bridge"
```

### General

Each modules needs to have a thread that can be joined in the main servunite-process. This thread contains all logic and handlers to process commands and events happening on the specified service.
